spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/financial?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    solr:
      host: http://127.0.0.1:8983/solr



mybatis:
  mapper-locations: classpath:mappers/*.xml















debug: true
